Food Ordering System With Rails
firte07/Rails-Food-Ordering pull request #1
Opened 2021-05-04 08:53 UTC by firte07

This pull request contains the whole functionality of the first assignment (Food ordering system) migrated in Rails.

In this PR you can find:

- SCSS website design (front page) and dashboard design in app/stylesheets (pages.scss and products.scss)
- HAML structure of the website and of the dashboard in app/views
- Ruby implementation of the whole website and dashboard

The first assignment repository is <a href="https://github.com/firte07/Food-ordering">here</a> along with the original website <a href="https://firte07.github.io/Food-ordering/">here</a> and the deploy site <a href="https://wolf-food-ordering.herokuapp.com//">here</a>.

Note: You can access the dashboard by adding /products to the url.

2021-05-05 06:23 UTC, vaneaclaudia requested changes

2021-05-05 06:23 UTC, vaneaclaudia commented on app/controllers/products_controller.rb
> +    @product = Product.new(product_params)
is the image also added here?

2021-05-05 06:23 UTC, vaneaclaudia commented on config/database.yml
> +  database: db/development.sqlite3
I think sqlite3 will not work with Heroku

2021-05-05 06:23 UTC, vaneaclaudia commented on db/migrate/20210428192143_create_products.rb
> +
you can also add `null` constraints when creating tables if needed like this:

`t.string :title, null: false`

2021-05-05 06:23 UTC, vaneaclaudia commented on test/controllers/products_controller_test.rb
> +  test "should show product" do
please update the test file to use single quotes instead of double quotes where you don't have string interpolation

2021-05-05 06:23 UTC, vaneaclaudia commented on test/system/products_test.rb
> +    fill_in "Description", with: @product.description
same remark regarding double quotes

2021-05-05 07:30 UTC, firte07 commented on app/controllers/products_controller.rb
> +    @product = Product.new(product_params)
yes, it is. I added on the line 54 the :image parameter and it works without the line: @product.image.attach(product_params[:image])

2021-05-05 07:31 UTC, firte07 commented on db/migrate/20210428192143_create_products.rb
> +
ok, thank you

2021-05-07 08:29 UTC, vaneaclaudia approved these changes

2021-05-07 09:03 UTC, chioreandan approved these changes

2021-05-07 09:23 UTC, merged